project_id = "gcntnilurlulejwwtpaa"

[functions.process-kalodata]
verify_jwt = true

[functions.process-kalodata-products]
verify_jwt = true

[functions.process-kalodata-creators]
verify_jwt = true

[functions.transcribe-video]
verify_jwt = false

[functions.rewrite-script]
verify_jwt = false

[functions.generate-script-variants]
verify_jwt = false
